<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/07/20 20:43:42

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=FatherStorm',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
